# Header
menu:                      # Links in the navigation bar
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

home:
  style: default           # default, detail

favicon:                   # Path to the custom favicon relative to /source (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: false                  # Display banner
  url:                           # Path to the banner image relative to /source. Web url is also supported
  position: center               # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true               # Display banner on all pages instead of only the home page

# Appearance
hue: 250                         # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)
                                 # Visit `saicaca.github.io/vivia-preview` to preview the theme color

# Personal info
avatar:                             # Path to the avatar image relative to /source
author: Your Name
subtitle: This is the subtitle
links:
  - name: Twitter
    icon: fa-brands fa-twitter      # Find icon codes at https://fontawesome.com/search
    url: https://twitter.com
  - name: Steam
    icon: fa-brands fa-steam
    url: https://store.steampowered.com
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
#      - archive
#      - recent_posts

# Sidebar Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5
categories:
  max_depth: 2             # Maximum depth of categories displayed in the widget (null for unlimited)

# Third-party comment system
comment:
  valine:
    enable: false         # Enable Valine comment system
    appId: 
    appKey: 
    placeholder: Just go go
    pageSize: 10
    highlight: true
    serverURLs: 
    # Other supported parameters can be added here if needed
    # Visit https://valine.js.org/configuration.html for more details
  twikoo:
    enable: false          # Enable Twikoo comment system
    envID:
    region:
    path: location.pathname
    lang:
    # See also: https://github.com/imaegoo/twikoo
  waline:
    enable: false          # Enable Waline comment system
    serverURL: 
    cdnJsURL: https://unpkg.com/@waline/client@2/dist/waline.mjs
    cdnCSSURL: https://unpkg.com/@waline/client@2/dist/waline.css
    # If you find that unpkg.com is inaccessible, you can try to use local files. 
    # Download the above two linked files to <hexo path>/source/waline, 
    # then comment the above two lines and uncomment the following two lines.
    # localJSURL: /waline/waline.mjs
    # localCSSURL: /waline/waline.css

#Analytics
gauges_analytics: false
google_analytics: false #UA-xxxxxx
baidu_analytics: false # ddxxxxxxxxxxxxxxxxx In the https://hm.baidu.com/hm.js? Afterwards
